name: 'Auto Publish Changeset Action'
description: 'Action to automatically publish a changeset when a PR is merged'
author: 'JamilOmar'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'
inputs:
  cwd:
    description: 'The current working directory'
    required: false
  commitMessage:
    description: 'The commit message to use when committing the changeset'
    required: true
    default: 'chore: publish changeset'
  publishScript:
    description: 'The script to run to publish the changeset'
    required: false
    default: ''
  versionScript:
    description: 'The script to run to bump the version'
    required: false
    default: ''
  username:
    description: 'The github name from the user'
    required: false
    default: ''
  email:
    description: 'The github email from the user'
    required: false
    default: ''
  force:
    description: 'Indicates if the github push should be forced'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  hadChangeset:
    description: 'Indicates if a changeset was found during the process'
runs:
  using: node20
  main: dist/index.js
